### ISSUE TITLE
Read JSON-LD stream

### ISSUE THREAD

**Issue by brechtvdv** [linkedconnections/arrdep2connections#4]
I'm trying to read a JSON-LD stream like in the test file with:

``` nodejs
  var arrivalsStream = fs.createReadStream('./test/data/arrivals.jsonldstream', {encoding: 'utf8'}).pipe(new jsonldstream.Deserializer());
```

This gives me following error:

``` bash
/Users/brechtvdv/School/thesis/arrdep2connections/test/data/arrivals.jsonldstream:1
on (exports, require, module, __filename, __dirname) { { "@context" : {"gtfs":
                                                                    ^
SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/brechtvdv/School/thesis/arrdep2connections/arrdep2connections.js:10:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

@pietercolpaert Do you know why this doesn't work?

**Comment by pietercolpaert** [comment]
Is this the development branch or own test code? In each case, it sounds like you shouldn't do "require" on a jsonld stream on line 10 of arrdep2connections/arrdep2connections.js

**Comment by brechtvdv** [comment]
Oh.. forgot to put old require(...) in comments..
Thanks for the quick response!
